'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, ArrowLeft, Building2, ClipboardList, Clock3, MessagesSquare, PlugZap, ShieldAlert, Stethoscope, Wrench } from 'lucide-react';

type Person={id:string;name:string;pillar?:string;programme?:string};
type User={id:string;email:string;role:string};
type Snapshot={
  user:User;people:Person[];users:User[];
  organisations:unknown[];sites:unknown[];providers:unknown[];programmeEnrollments:unknown[];communications:unknown[];assessments:unknown[];careTime:unknown[];
  supportTickets:unknown[];connectors:unknown[];workflowRules:unknown[];clinicalAlertRules:unknown[];roleAssignments:unknown[];conditions:unknown[];medications:unknown[];
};

async function request(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
function Field({label,name,children,required=true}:{label:string;name?:string;children?:ReactNode;required?:boolean}){return <label className="field">{label}{children||<input name={name} required={required} maxLength={500}/>}</label>}

export default function OperationsPage(){
  const [data,setData]=useState<Snapshot|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [section,setSection]=useState('Care operations');
  const refresh=useCallback(async()=>{try{setData(await request('/api/workspace/'));setMessage('');}catch(error){setMessage((error as Error).message);setData(null);}},[]);
  useEffect(()=>{refresh();},[refresh]);
  const counts=useMemo(()=>data?{
    organisations:data.organisations.length,sites:data.sites.length,providers:data.providers.length,enrolments:data.programmeEnrollments.length,communications:data.communications.length,assessments:data.assessments.length,
    time:data.careTime.length,tickets:data.supportTickets.length,connectors:data.connectors.length,automations:data.workflowRules.length,alertRules:data.clinicalAlertRules.length,roles:data.roleAssignments.length,
  }:null,[data]);
  async function submit(action:string,event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=event.currentTarget;try{const fields=Object.fromEntries(new FormData(form));await request('/api/workspace/','POST',{...fields,action});form.reset();await refresh();setMessage('Changes saved.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
  if(!data)return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/"><ArrowLeft size={16}/> CareGrid workspace</Link><div className="clinical-brand"><Activity/> CareGrid</div></header><section className="clinical-section"><h1>CareGrid operations</h1><p>{message||'Opening the authenticated workspace…'}</p><Link href="/">Sign in or return to workspace</Link></section></div></main>;
  const personOptions=<><option value="">Choose a person</option>{data.people.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</>;
  const userOptions=<><option value="">Choose a user</option>{data.users.map(user=><option key={user.id} value={user.id}>{user.email}</option>)}</>;
  const sections=['Care operations','Enterprise','Integrations','Governance'];
  return <main className="clinical-page"><div className="clinical-shell">
    <header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><Activity/> CareGrid Operations</div></header>
    <section className="clinical-hero"><span className="eyebrow">LIVE EXPANDED WORKSPACE</span><h1>Run the wider care platform.</h1><p>These modules use the same authenticated CareGrid workspace, persistence layer and audit history as the existing RPM experience.</p></section>
    <div className="clinical-chip-row">{sections.map(name=><button className="secondary" key={name} onClick={()=>setSection(name)} aria-pressed={section===name}>{name}</button>)}</div>
    {message&&<p className="live-notice" role="status">{message}</p>}
    <section className="metrics"><article><span>Program enrollments</span><strong>{counts?.enrolments}</strong></article><article><span>Communications</span><strong>{counts?.communications}</strong></article><article><span>Assessments</span><strong>{counts?.assessments}</strong></article><article><span>Support tickets</span><strong>{counts?.tickets}</strong></article></section>

    {section==='Care operations'&&<>
      <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">MULTI-PROGRAM CARE</span><h2>Program enrollment</h2></div><Stethoscope/></div><form className="live-form" onSubmit={e=>submit('programme-enrolment',e)}><Field label="Person"><select name="personId" required>{personOptions}</select></Field><Field label="Program" name="programme"/><Field label="Clinical pillar" name="pillar" required={false}/><button className="primary" disabled={busy}>Enroll in program</button></form></section>
      <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">ENGAGEMENT</span><h2>Communication log</h2></div><MessagesSquare/></div><form className="live-form" onSubmit={e=>submit('communication',e)}><Field label="Person"><select name="personId" required>{personOptions}</select></Field><Field label="Channel"><select name="channel"><option>phone</option><option>sms</option><option>email</option><option>secure-message</option><option>video</option></select></Field><Field label="Direction"><select name="direction"><option>outbound</option><option>inbound</option></select></Field><Field label="Subject" name="subject" required={false}/><Field label="Outcome" name="outcome" required={false}/><label className="field">Note<textarea name="body" rows={4}/></label><button className="primary" disabled={busy}>Log communication</button></form></section>
      <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">ASSESSMENTS</span><h2>Questionnaire result</h2></div><ClipboardList/></div><form className="live-form" onSubmit={e=>submit('assessment',e)}><Field label="Person"><select name="personId" required>{personOptions}</select></Field><Field label="Instrument"><select name="instrument"><option>PHQ-2</option><option>PHQ-9</option><option>GAD-7</option><option>Custom</option></select></Field><Field label="Version" name="version"/><Field label="Score" name="score" required={false}/><button className="primary" disabled={busy}>Record assessment</button></form></section>
      <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">CARE MANAGEMENT</span><h2>Time tracking</h2></div><Clock3/></div><form className="live-form" onSubmit={e=>submit('care-time',e)}><Field label="Person"><select name="personId" required>{personOptions}</select></Field><Field label="Activity type" name="activityType"/><Field label="Program" name="programme" required={false}/><Field label="Duration seconds"><input name="durationSeconds" type="number" min="0" required/></Field><Field label="Notes" name="notes" required={false}/><button className="primary" disabled={busy}>Record care time</button></form></section>
      <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">DEVICE SUPPORT</span><h2>Support ticket</h2></div><Wrench/></div><form className="live-form" onSubmit={e=>submit('support-ticket',e)}><Field label="Person"><select name="personId">{personOptions}</select></Field><Field label="Device ID" name="deviceId" required={false}/><Field label="Category" name="category"/><Field label="Priority"><select name="priority"><option>normal</option><option>high</option><option>urgent</option></select></Field><Field label="Summary" name="summary"/><button className="primary" disabled={busy}>Open ticket</button></form></section>
    </>}

    {section==='Enterprise'&&<>
      <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">MULTI-TENANT</span><h2>Organisations, sites and providers</h2></div><Building2/></div><div className="metrics"><article><span>Organisations</span><strong>{counts?.organisations}</strong></article><article><span>Sites</span><strong>{counts?.sites}</strong></article><article><span>Providers</span><strong>{counts?.providers}</strong></article><article><span>Expanded roles</span><strong>{counts?.roles}</strong></article></div><form className="live-form" onSubmit={e=>submit('organisation',e)}><Field label="Organisation name" name="name"/><button className="primary" disabled={busy}>Create organisation</button></form><form className="live-form" onSubmit={e=>submit('site',e)}><Field label="Site name" name="name"/><Field label="Organisation ID" name="organisationId" required={false}/><Field label="Address" name="address" required={false}/><Field label="Town" name="town" required={false}/><button className="primary" disabled={busy}>Create site</button></form><form className="live-form" onSubmit={e=>submit('provider',e)}><Field label="Provider name" name="name"/><Field label="Provider type" name="providerType" required={false}/><Field label="Organisation ID" name="organisationId" required={false}/><Field label="Site ID" name="siteId" required={false}/><button className="primary" disabled={busy}>Create provider</button></form></section>
      <section className="clinical-section"><h2>Role assignment</h2><form className="live-form" onSubmit={e=>submit('role-assignment',e)}><Field label="User"><select name="userId" required>{userOptions}</select></Field><Field label="Expanded role"><select name="role"><option>platform-admin</option><option>organisation-admin</option><option>clinical-admin</option><option>physician</option><option>nurse</option><option>care-manager</option><option>reviewer</option><option>device-technician</option><option>billing</option><option>analyst</option><option>auditor</option></select></Field><Field label="Organisation ID" name="organisationId" required={false}/><Field label="Site ID" name="siteId" required={false}/><button className="primary" disabled={busy}>Assign role</button></form></section>
    </>}

    {section==='Integrations'&&<>
      <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">FHIR · HL7 · REST · DEVICE CLOUDS</span><h2>Connector registry</h2></div><PlugZap/></div><p>{counts?.connectors} connector definitions are currently registered.</p><form className="live-form" onSubmit={e=>submit('connector',e)}><Field label="Connector name" name="name"/><Field label="Connector type"><select name="connectorType"><option>FHIR</option><option>HL7</option><option>REST</option><option>device-cloud</option><option>gateway</option></select></Field><Field label="Endpoint" name="endpoint" required={false}/><Field label="Version" name="version" required={false}/><button className="primary" disabled={busy}>Register connector</button></form></section>
      <section className="clinical-section"><h2>Operational workflow automation</h2><p>Automation is intentionally non-clinical. Clinical decisions use the governed alert-rule workflow.</p><form className="live-form" onSubmit={e=>submit('workflow-rule',e)}><Field label="Rule name" name="name"/><Field label="Trigger"><select name="triggerType"><option>missed-reading</option><option>stale-device</option><option>care-plan-review-due</option><option>assessment-completed</option><option>task-overdue</option></select></Field><Field label="Action"><select name="actionType"><option>create-task</option><option>notify-care-manager</option><option>send-reminder</option><option>escalate-task</option></select></Field><button className="primary" disabled={busy}>Create automation</button></form></section>
    </>}

    {section==='Governance'&&<section className="clinical-section clinical-safety"><div className="clinical-section-heading"><div><span className="eyebrow">GOVERNED CLINICAL ALERTS</span><h2>Clinical rule registry</h2></div><ShieldAlert/></div><p>Rules are created disabled. Enabling them requires a separately approved clinical response workflow and governance process.</p><p>{counts?.alertRules} governed rule definitions currently exist.</p><form className="live-form" onSubmit={e=>submit('clinical-alert-rule',e)}><Field label="Rule name" name="name"/><Field label="Metric" name="metric"/><Field label="Governance reference" name="governanceReference"/><label className="field">Rule definition (JSON)<textarea name="rule" rows={4} placeholder='{"operator":"configured-outside-software"}'/></label><button className="primary" disabled={busy}>Register disabled rule</button></form></section>}
  </div></main>;
}
