'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowLeft, Filter, UsersRound } from 'lucide-react';

type Person={id:string;name:string;town:string;pillar:string;programme:string;active:number};type Row=Record<string,unknown>;type Snapshot={people:Person[];cohorts:Row[];programmeEnrollments:Row[];attention:Row[]};
async function req(method='GET',body?:unknown){const response=await fetch('/api/workspace/',{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
export default function Population(){const [data,setData]=useState<Snapshot|null>(null);const [query,setQuery]=useState('');const [pillar,setPillar]=useState('All');const [programme,setProgramme]=useState('All');const [message,setMessage]=useState('');async function refresh(){try{setData(await req());setMessage('');}catch(error){setMessage((error as Error).message);}}useEffect(()=>{refresh();},[]);const visible=useMemo(()=>data?.people.filter(person=>(pillar==='All'||person.pillar===pillar)&&(programme==='All'||person.programme===programme)&&`${person.name} ${person.town} ${person.pillar} ${person.programme}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query,pillar,programme]);async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;try{await req('POST',{action:'cohort',name:String(new FormData(form).get('name')||''),filters:JSON.stringify({query,pillar,programme})});form.reset();await refresh();setMessage('Cohort saved.');}catch(error){setMessage((error as Error).message);}}
 const pillars=[...new Set(data?.people.map(p=>p.pillar)||[])];const programmes=[...new Set(data?.people.map(p=>p.programme)||[])];
 return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><UsersRound/> Population Management</div></header><section className="clinical-hero"><span className="eyebrow">COHORTS & SEGMENTATION</span><h1>Move from one record to the whole care population.</h1><p>Filter by CareGrid clinical pillar, existing program, person context and saved cohorts without duplicating patient records.</p></section>{message&&<p className="live-notice">{message}</p>}
 {data&&<><section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">FILTERS</span><h2>Population filter</h2></div><Filter/></div><div className="live-form"><label className="field">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, town, pathway…"/></label><label className="field">Clinical pillar<select value={pillar} onChange={e=>setPillar(e.target.value)}><option>All</option>{pillars.map(value=><option key={value}>{value}</option>)}</select></label><label className="field">Program<select value={programme} onChange={e=>setProgramme(e.target.value)}><option>All</option>{programmes.map(value=><option key={value}>{value}</option>)}</select></label></div><p><strong>{visible.length}</strong> of {data.people.length} people match this view.</p><form className="live-form" onSubmit={save}><label className="field">Save this cohort as<input name="name" required/></label><button className="primary">Save cohort</button></form></section>
 <section className="clinical-section"><h2>Matching people</h2><div className="clinical-grid">{visible.map(person=><Link className="clinical-card" href={`/people/${person.id}/`} key={person.id}><span className="eyebrow">{person.pillar}</span><h3>{person.name}</h3><p>{person.town} · {person.programme} · {person.active?'active':'paused'}</p></Link>)}</div></section>
 <section className="clinical-section"><h2>Saved cohorts</h2><div className="clinical-grid">{data.cohorts.map((row,index)=><article className="clinical-card" key={String(row.id||index)}><h3>{String(row.name||'Cohort')}</h3><p>{String(row.filters||'{}')}</p></article>)}</div></section></>}
 </div></main>}
