import { test, expect } from '@playwright/test';
test('stored workspace supports enrolment, authenticated ingestion, tasks and logout', async ({ page, request }) => {
  await page.goto('/');
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test');
  await page.getByLabel('Password · at least 14 characters', { exact: true }).fill('browser-test-password-long');
  await page.getByRole('button', { name: 'Create administrator' }).click();
  await expect(page.getByRole('heading', { name: 'A clearer view of care.' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'No automatic readings yet' })).toBeVisible();
  await page.getByRole('button', { name: 'People', exact: true }).click();
  await page.getByLabel('Full name').fill('Browser Test Person');
  await page.getByLabel('Town', { exact: true }).fill('Cape Town');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Save person' }).click();
  await expect(page.getByRole('button', { name: 'Browser Test Person', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Workspace', exact: true }).click();
  await page.getByLabel('Integration name').fill('Browser gateway');
  await page.getByLabel('Adapter ID · e.g. clinic-gateway-adapter').fill('browser-adapter');
  await page.getByRole('button', { name: 'Register integration' }).click();
  await expect(page.getByLabel('Bearer token')).toBeVisible();
  const secret = await page.getByLabel('Bearer token').inputValue();
  await page.getByRole('button', { name: 'I have saved it · dismiss' }).click();
  await page.getByRole('button', { name: 'Devices', exact: true }).click();
  await page.getByLabel('Connector device ID').fill('browser-device');
  await page.getByLabel('Device label', { exact: true }).fill('Test oximeter');
  await page.getByRole('combobox', { name: 'Person', exact: true }).selectOption({ label: 'Browser Test Person' });
  await page.getByRole('combobox', { name: 'Integration', exact: true }).selectOption({ label: 'Browser gateway' });
  await page.getByRole('combobox', { name: 'Measurement', exact: true }).selectOption('spo2');
  await page.getByRole('button', { name: 'Enrol device', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Test oximeter' })).toBeVisible();
  const payload = { source: 'browser-adapter', sourceEventId: 'browser-event-1', deviceId: 'browser-device', measuredAt: new Date().toISOString(), measurement: { kind: 'spo2', value: 98, unit: '%' } };
  const headers = { Authorization: `Bearer ${secret}`, 'X-CareGrid-Adapter': 'browser-adapter' };
  expect((await request.post('/api/readings/', { data: payload })).status()).toBe(401);
  expect((await request.post('/api/readings/', { headers, data: payload })).status()).toBe(201);
  expect((await request.post('/api/readings/', { headers, data: payload })).status()).toBe(200);
  expect((await request.post('/api/readings/', { headers, data: { ...payload, measurement: { kind: 'spo2', value: 97, unit: '%' } } })).status()).toBe(409);
  expect((await request.get('/api/workspace/')).status()).toBe(401);
  expect((await page.request.post('/api/workspace/', { headers: { Origin: 'https://untrusted.example' }, data: { action: 'person' } })).status()).toBe(403);
  await page.getByRole('button', { name: 'Reports', exact: true }).click();
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.getByRole('cell', { name: '98 %', exact: true })).toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download readings CSV' }).click();
  expect((await download).suggestedFilename()).toBe('caregrid-readings.csv');
  await page.getByRole('button', { name: 'Tasks', exact: true }).click();
  await page.getByRole('combobox', { name: 'Person', exact: true }).selectOption({ label: 'Browser Test Person' });
  await page.getByLabel('What needs to happen?').fill('Review device setup');
  await page.getByRole('button', { name: 'Create task', exact: true }).click();
  await page.getByRole('combobox', { name: 'Owner', exact: true }).selectOption({ label: 'browser@example.test' });
  await page.getByRole('combobox', { name: 'Stage', exact: true }).selectOption('Completed');
  await page.getByRole('button', { name: 'Save task', exact: true }).click();
  await expect(page.locator('.badge').filter({ hasText: 'Completed' })).toBeVisible();
  await page.reload();
  await expect(page.locator('.badge').filter({ hasText: 'Completed' })).toBeVisible();
  for (const width of [390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  await page.screenshot({ path: 'test-results/persistent-workspace.png', fullPage: true });
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  expect((await page.request.get('/api/workspace/')).status()).toBe(401);
});
