'use client';

import Link from 'next/link';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, BadgeDollarSign, Landmark, LineChart } from 'lucide-react';

type Person={id:string;name:string};type Row=Record<string,unknown>;type Snapshot={people:Person[];billingRules:Row[];billingActivity:Row[];qualityMeasures:Row[];careTime:Row[]};
async function req(method='GET',body?:unknown){const response=await fetch('/api/workspace/',{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
export default function Finance(){const [data,setData]=useState<Snapshot|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function refresh(){try{setData(await req());setMessage('');}catch(error){setMessage((error as Error).message);}}useEffect(()=>{refresh();},[]);async function submit(action:string,event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget;try{await req('POST',{...Object.fromEntries(new FormData(form)),action});form.reset();await refresh();setMessage('Changes saved.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 const people=<><option value="">Choose a person</option>{data?.people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</>;
 const total=data?.billingActivity.reduce((sum,row)=>sum+Number(row.amount_estimate||0),0)||0;const minutes=Math.round((data?.careTime.reduce((sum,row)=>sum+Number(row.duration_seconds||0),0)||0)/60);
 return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><BadgeDollarSign/> Finance & Quality</div></header><section className="clinical-hero"><span className="eyebrow">JURISDICTION-NEUTRAL BILLING</span><h1>Track care activity without hardcoding one payer model.</h1><p>Billing rules are versioned, deployment-specific and inactive by default. Care delivery remains separate from reimbursement logic.</p></section>{message&&<p className="live-notice">{message}</p>}
 {data&&<><section className="metrics"><article><span>Billing rule definitions</span><strong>{data.billingRules.length}</strong></article><article><span>Billing activity rows</span><strong>{data.billingActivity.length}</strong></article><article><span>Care time</span><strong>{minutes} min</strong></article><article><span>Estimated amount</span><strong>{total.toLocaleString('en-ZA',{maximumFractionDigits:2})}</strong></article></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">RULES</span><h2>Create billing rule definition</h2></div><Landmark/></div><p>New billing rules are stored inactive until reviewed for the relevant jurisdiction and payer.</p><form className="live-form" onSubmit={e=>submit('billing-rule',e)}><label className="field">Jurisdiction<input name="jurisdiction" required placeholder="South Africa"/></label><label className="field">Program<input name="programme"/></label><label className="field">Rule code<input name="ruleCode" required/></label><label className="field">Version<input name="version" defaultValue="1"/></label><label className="field">Definition JSON<textarea name="definition" rows={4} placeholder='{"basis":"configured by payer"}'/></label><button className="primary" disabled={busy}>Store inactive rule</button></form></section>
 <section className="clinical-section"><h2>Record billing-ready activity</h2><form className="live-form" onSubmit={e=>submit('billing-activity',e)}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Program<input name="programme"/></label><label className="field">Period<input name="period" required placeholder="2026-09"/></label><label className="field">Rule code<input name="ruleCode"/></label><label className="field">Estimated amount<input name="amountEstimate" type="number" step="0.01"/></label><label className="field">Currency<input name="currency" placeholder="ZAR"/></label><label className="field">Status<select name="status"><option>draft</option><option>review</option><option>ready</option><option>exported</option></select></label><button className="primary" disabled={busy}>Save billing activity</button></form></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">QUALITY</span><h2>Quality measure registry</h2></div><LineChart/></div><p>{data.qualityMeasures.length} active quality measure definitions.</p><form className="live-form" onSubmit={e=>submit('quality-measure',e)}><label className="field">Measure code<input name="code" required/></label><label className="field">Name<input name="name" required/></label><label className="field">Framework<input name="framework" required placeholder="Internal, HEDIS, Stars, custom…"/></label><label className="field">Version<input name="version" defaultValue="1"/></label><label className="field">Definition JSON<textarea name="definition" rows={4}/></label><button className="primary" disabled={busy}>Add quality measure</button></form></section></>}
 </div></main>}
