'use client';
import { useState } from 'react';
import { useDemoSession } from './useDemoSession';

import CareTasks from './CareTasks';
import Reports from './Reports';
import { Activity, LayoutDashboard, Users, ListChecks, FileSpreadsheet, Bell, Radio, Settings, ArrowUpRight, ArrowLeft, Search, Check, ChevronRight, ShieldCheck, RotateCcw } from 'lucide-react';
import { alerts, patients, filterPatients, type Patient } from '../../lib/demo';
import { clinicalPillars } from '../../lib/care-plans';
import { useWorkspaceRoute } from './useWorkspaceRoute';
import type { View } from '../../lib/navigation';

const navigation = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'People', icon: Users }, { label: 'Alerts', icon: Bell }, { label: 'Devices', icon: Radio }, { label: 'Tasks', icon: ListChecks }, { label: 'Reports', icon: FileSpreadsheet }, { label: 'Workspace', icon: Settings }] as const;

function Trend({ patient }: { patient: Patient }) {
  const low = Math.min(...patient.readings) - 1, range = Math.max(...patient.readings) - low + 1;
  const points = patient.readings.map((v, i) => `${20 + i * 60},${150 - (v - low) / range * 115}`).join(' ');
  return <figure className="trend"><svg viewBox="0 0 460 180" role="img" aria-label={`${patient.metric} sample trend: ${patient.readings.join(', ')} ${patient.unit}`}><path d="M20 35H440M20 90H440M20 145H440" stroke="#e1e8ed" strokeDasharray="4 5" /><polyline points={points} fill="none" stroke="currentColor" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" />{patient.readings.map((v, i) => <circle key={i} cx={20 + i * 60} cy={150 - (v - low) / range * 115} r="3.5" fill="currentColor" />)}</svg><figcaption>Eight illustrative readings · sequence, not elapsed time</figcaption></figure>;
}

export default function CareGrid() {
  const [resetKey, setResetKey] = useState(0);
  const demo=useDemoSession(); const {workflow,acknowledged}=demo.session; const {dispatchWorkflow}=demo;
  const {route,go}=useWorkspaceRoute();
  const view=route.view;
  const selected=patients.find(p=>p.id===route.personId)||null;
  const alertPerson=patients.find(p=>p.id===route.alertPersonId)||null;
  const [query, setQuery] = useState('');
  const [pillar, setPillar] = useState('All pillars');
  const [alertFilter, setAlertFilter] = useState('Open');
  const [status, setStatus] = useState('');
  const openAlerts = alerts.filter(a => !acknowledged.includes(a.id));
  const filtered = filterPatients(query, pillar);
  const connectedDevices = patients.filter(p=>p.connected).length;

  function navigate(next: View) { go({view:next,personId:null,alertPersonId:null}); setStatus(''); }
  function reviewPerson(id:string){go({view:'Alerts',personId:null,alertPersonId:id});setAlertFilter('All');setStatus('');}
  function acknowledge(id: string) { const was = acknowledged.includes(id); demo.acknowledge(id); setStatus(was ? 'Sample alert reopened.' : 'Sample alert acknowledged. No patient contact or clinical action was performed.'); }
  function person(p: Patient) {go({view:'People',personId:p.id,alertPersonId:null});setStatus('');}
  function showPillar(name:string){setPillar(name);navigate('People');}
  function roster(list: Patient[]) { return <div className="roster">{list.map(p => <button className="person" key={p.id} onClick={() => person(p)}><span className="avatar">{p.initials}</span><span className="person-name"><strong>{p.name}</strong><small>{p.id} · {p.town} · {p.programme}</small></span><span className="programme">{p.pillar}</span><span className={`badge ${p.connected ? 'good' : 'amber'}`}>{p.connected ? 'Device available' : 'Connection check'}</span><ChevronRight size={17} /></button>)}</div>; }
  function alertList() { const list = alerts.filter(a => (!alertPerson || a.patientId===alertPerson.id) && (alertFilter === 'All' || (alertFilter === 'Acknowledged' ? acknowledged.includes(a.id) : !acknowledged.includes(a.id)))); return <>{alertPerson && <div className="patient-scope"><span>Review queue for <strong>{alertPerson.name}</strong></span><button className="text-button" onClick={()=>navigate('Alerts')}>Show all people</button></div>}<div className="tabs" aria-label="Filter alerts">{['Open', 'Acknowledged', 'All'].map(f => <button key={f} aria-pressed={alertFilter === f} onClick={() => setAlertFilter(f)}>{f}</button>)}</div>{list.length ? <div className="alerts">{list.map(a => { const p = patients.find(p => p.id === a.patientId)!; const done = acknowledged.includes(a.id); return <article className="alert" key={a.id}><span className={`alert-symbol ${done ? 'done' : ''}`}>{done ? <Check size={21} /> : a.kind === 'device' ? <Radio size={21} /> : <Activity size={21} />}</span><div><small>{a.time} SAST · {p.id} · {p.pillar}</small><h3>{a.title}</h3><button className="text-button" onClick={() => person(p)}>{p.name} <ArrowUpRight size={14} /></button><p>{a.description}</p><div className="actions"><button className="secondary" onClick={()=>{const exists=workflow.tasks.some(t=>t.alertId===a.id);dispatchWorkflow({type:'from-alert',alertId:a.id});navigate('Tasks');setResetKey(k=>k+1);setStatus(exists ? 'Existing follow-up shown in Tasks.' : 'Sample follow-up created. Assign an owner in Tasks.');}}>{workflow.tasks.some(t=>t.alertId===a.id) ? 'View follow-up' : 'Create follow-up'}</button><button className="secondary" onClick={() => acknowledge(a.id)}>{done ? 'Reopen sample alert' : 'Acknowledge'}</button><span className={`badge ${done ? 'good' : 'amber'}`}>{done ? 'Acknowledged' : 'Awaiting review'}</span></div></div></article>; })}</div> : <div className="empty"><Check size={30} /><h3>{alertFilter === 'All' ? 'No alerts' : `No ${alertFilter.toLowerCase()} alerts`}</h3><p>Change the filter to explore the sample workflow.</p></div>}</>; }

  return <div className="shell"><a className="skip" href="#main">Skip to workspace</a><aside className="sidebar"><a className="brand" href="./"><span className="brand-mark"><Activity size={25} /></span>Care<span>Grid</span></a><p className="workspace-label">HOMECLINICSTORE / CARE TEAM</p><nav aria-label="Main navigation">{navigation.map(({ label, icon: Icon }) => <button key={label} onClick={() => navigate(label)} aria-current={view === label ? 'page' : undefined}><Icon size={19} /><span>{label}</span>{label === 'Alerts' && openAlerts.length > 0 && <b>{openAlerts.length}</b>}</button>)}</nav><div className="sidebar-note"><ShieldCheck size={23} /><strong>Four pathways. One care view.</strong><p>Diabetes. Hypertension. Cardiovascular health. Stroke prevention.</p></div><div className="team"><span className="avatar">HC</span><div><strong>HomeClinicStore</strong><small>Demonstration workspace</small></div></div></aside><div className="workspace"><header className="topbar"><span>Workspace <ChevronRight size={13} /> <strong>{selected ? selected.name : view}</strong></span><span className="demo-pill">Demo environment</span></header><main id="main"><div className="demo-notice"><span className="dot" /><span>Fictional people and sample readings. No live monitoring, diagnosis, emergency detection or clinical decisions. Demo activity stays in this tab until reset.</span></div><div className="session-status"><span>{demo.mode === 'saved' ? 'Demo session saved in this tab' : demo.mode === 'memory' ? 'Demo session: memory only' : 'Opening demo session…'}</span>{demo.notice && <p role="status">{demo.notice}</p>}</div><div role="status" className={status ? 'status' : 'sr-only'}>{status}</div>
  {selected ? <><button className="text-button back" onClick={() => navigate('People')}><ArrowLeft size={16} /> Back to people</button><div className="page-heading"><div><span className="eyebrow">{selected.pillar.toUpperCase()} / {selected.id}</span><h1 tabIndex={-1}>{selected.name}</h1><p>{selected.programme} · {selected.town}, South Africa</p></div><span className="badge">Fictional profile</span></div><div className="detail-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">{selected.metric}</span><h2>{selected.readings.at(-1)} <small>{selected.unit}</small></h2></div><span className="muted">Sample · {selected.last}</span></div><Trend patient={selected} /><details><summary>View accessible reading table</summary><table><thead><tr><th>Sequence</th><th>{selected.metric} ({selected.unit})</th></tr></thead><tbody>{selected.readings.map((v,i) => <tr key={i}><td>{i+1}</td><td>{v}</td></tr>)}</tbody></table></details></section><section className="panel"><span className="eyebrow">CONNECTED DEVICE</span><h2>{selected.device}</h2><dl><div><dt>Clinical pillar</dt><dd>{selected.pillar}</dd></div><div><dt>Programme</dt><dd>{selected.programme}</dd></div><div><dt>Status</dt><dd>{selected.connected ? 'Available in demo' : 'Connection check'}</dd></div><div><dt>Battery</dt><dd>{selected.battery}%</dd></div><div><dt>Latest sample</dt><dd>{selected.last} SAST</dd></div></dl><p className="muted">Device status is illustrative. No physical device is paired with this workspace.</p></section></div><section className="panel context"><h2>Context before action.</h2><p>This profile sits within the {selected.pillar.toLowerCase()} pathway. In a production care service, interpretation and follow-up depend on a clinician-agreed plan, measurement context and verified device data. This demo does not classify readings or recommend treatment.</p><button className="secondary" onClick={() => { reviewPerson(selected.id); }}>Review alerts for this person <ArrowUpRight size={16} /></button></section></> : <>
  <div className="page-heading"><div><span className="eyebrow">CONNECTED CARE AT HOME</span><h1 tabIndex={-1}>{view === 'Overview' ? 'Four pathways. One clearer view.' : view === 'People' ? 'People, not just readings.' : view === 'Alerts' ? 'Attention, with context.' : view === 'Devices' ? 'The connections behind care.' : view === 'Tasks' ? 'Follow-through, made visible.' : view === 'Reports' ? 'A shared view of progress.' : 'Your care workspace.'}</h1><p>{view === 'Overview' ? 'Diabetes, hypertension, cardiovascular health and stroke prevention brought into one connected-care workflow.' : view === 'People' ? 'Explore fictional people across CareGrid’s four clinical pillars.' : view === 'Alerts' ? 'Review and acknowledge sample tasks. Acknowledgement is not resolution.' : view === 'Devices' ? 'Understand device availability before interpreting missing readings.' : view === 'Tasks' ? 'Give sample follow-ups an owner and a clear next step.' : view === 'Reports' ? 'Review and export the fictional activity in your current session.' : 'A transparent foundation for a connected-care service.'}</p></div><span className="date">17 September 2026 <small>Sample day · SAST (UTC+2)</small></span></div>
  {view === 'Overview' && <><div className="metrics"><article><span>People in the workspace</span><strong>{patients.length.toString().padStart(2,'0')}</strong><small>Across four clinical pillars</small></article><article><span>Awaiting review</span><strong>{openAlerts.length.toString().padStart(2,'0')}<i /></strong><small>Sample items for your team</small></article><article><span>Devices available</span><strong>{String(connectedDevices).padStart(2,'0')} <em>/ {String(patients.length).padStart(2,'0')}</em></strong><small>{patients.length-connectedDevices} connection to check</small></article></div><section className="panel" style={{marginBottom:'1.5rem'}}><div className="panel-heading"><div><span className="eyebrow">CLINICAL FOUNDATION</span><h2>CareGrid’s four pillars</h2></div></div><div className="metrics">{clinicalPillars.map(({name,description})=><article key={name}><span>{name}</span><strong>{String(patients.filter(p=>p.pillar===name).length).padStart(2,'0')}</strong><small>{description}</small><button className="text-button" onClick={()=>showPillar(name)}>View pathway <ArrowUpRight size={14}/></button></article>)}</div></section><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">YOUR NEXT STEP</span><h2>Review queue</h2></div><button className="text-button" onClick={() => navigate('Alerts')}>View all <ArrowUpRight size={16} /></button></div>{openAlerts.length ? openAlerts.map(a => {const p=patients.find(person=>person.id===a.patientId);return <button className="queue-item" key={a.id} onClick={() => navigate('Alerts')}><span className="queue-dot" /><span><strong>{a.title}</strong><small>{p?.name} · {p?.pillar} · {a.time} SAST</small></span><ChevronRight size={18} /></button>}) : <div className="empty">All sample tasks acknowledged.</div>}</section><section className="feature-panel"><span className="eyebrow">THE CAREGRID APPROACH</span><h2>Good care starts<br />with the whole picture.</h2><p>Bring connected readings, prevention pathways and the people behind them into one considered workflow.</p><div className="flow"><span>Device</span><ChevronRight size={15} /><span>Context</span><ChevronRight size={15} /><span>Care team</span></div><button onClick={() => navigate('Workspace')}>About this workspace <ArrowUpRight size={17} /></button></section></div><section className="panel"><div className="panel-heading"><h2>People in view</h2><button className="text-button" onClick={() => navigate('People')}>Explore people <ArrowUpRight size={16} /></button></div>{roster(patients)}</section></>}
  {view === 'People' && <section className="panel"><div className="filters"><label className="search"><Search size={18} /><span className="sr-only">Search name, ID, town, programme or pillar</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people, town or pathway" /></label><label><span className="sr-only">Clinical pillar</span><select value={pillar} onChange={e=>setPillar(e.target.value)}><option>All pillars</option>{clinicalPillars.map(item=><option key={item.name}>{item.name}</option>)}</select></label><span className="muted" role="status">{filtered.length} people</span></div>{filtered.length ? roster(filtered) : <div className="empty"><Search size={26} /><h2>No matching people</h2><p>Try a different name, town or clinical pillar.</p><button className="secondary" onClick={()=>{setQuery('');setPillar('All pillars');}}>Clear filters</button></div>}</section>}
  {view === 'Alerts' && <section className="panel">{alertList()}</section>}
  {view === 'Devices' && <div className="device-grid">{patients.map(p=><article className="panel" key={p.id}><div className="panel-heading"><span className="device-icon"><Radio size={26} /></span><span className={`badge ${p.connected?'good':'amber'}`}>{p.connected?'Available':'Check connection'}</span></div><span className="eyebrow">{p.pillar}</span><h2>{p.device}</h2><button className="text-button" onClick={()=>person(p)}>{p.name}<ArrowUpRight size={14}/></button><dl><div><dt>Programme</dt><dd>{p.programme}</dd></div><div><dt>Demo identifier</dt><dd>DEV-{p.id}</dd></div><div><dt>Battery</dt><dd>{p.battery}%</dd></div><div><dt>Last sample</dt><dd>{p.last}</dd></div></dl><meter min={0} max={100} value={p.battery} aria-label={`${p.name} device battery`} /><p className="muted">Illustrative status · no device connection</p></article>)}</div>}
  {view === 'Reports' && <Reports workflow={workflow} acknowledged={acknowledged}/>} 
  {view === 'Workspace' && <><section className="panel" style={{marginBottom:'1.5rem'}}><span className="eyebrow">CLINICAL MODEL</span><h2>Four pillars guide the product.</h2><p>The same pillars shape dashboards, monitoring workflows, care plans, alerts and future device integrations.</p><div className="metrics">{clinicalPillars.map(({name,description})=><article key={name}><span>{name}</span><small>{description}</small></article>)}</div></section><div className="detail-grid"><section className="panel"><span className="eyebrow">FIRST RELEASE</span><h2>Built around a human workflow.</h2><p>CareGrid brings fictional people, measurements and review tasks together so you can evaluate the care-team experience before connecting real services.</p><dl><div><dt>Organisation</dt><dd>HomeClinicStore</dd></div><div><dt>Region</dt><dd>South Africa</dd></div><div><dt>Time zone</dt><dd>Africa/Johannesburg</dd></div><div><dt>Clinical pillars</dt><dd>4</dd></div><div><dt>Data mode</dt><dd>Fictional samples only</dd></div><div><dt>Demo storage</dt><dd>{demo.mode === 'saved' ? 'This browser tab' : 'Page memory'}</dd></div></dl><button className="secondary" onClick={()=>{demo.reset();setResetKey(key=>key+1);setQuery('');setPillar('All pillars');setAlertFilter('Open');setStatus('Demo reset. Sample alerts, tasks and activity history have been reset.');}}><RotateCcw size={16}/> Reset demo activity</button></section><section className="panel"><span className="eyebrow">BEFORE REAL-WORLD USE</span><h2>Connect your device ecosystem.</h2><p>One automatic reading format for supported devices and services, across brands.</p><dl><div><dt>Measurements</dt><dd>Blood pressure, glucose, SpO2 and compatible future metrics</dd></div><div><dt>Connection routes</dt><dd>Approved device gateways and cloud services</dd></div><div><dt>Reading entry</dt><dd>Automatic only</dd></div><div><dt>Live integrations</dt><dd>Not connected</dd></div></dl><p>Each connector must be verified and each device assigned to a person before readings are accepted.</p><ul className="readiness"><li>Authenticated accounts and role-based access</li><li>Consent, privacy controls and retention rules</li><li>Verified device integrations and data provenance</li><li>Clinician-agreed alert and response workflows</li><li>Secure audit history and operational support</li></ul><p className="muted">This prototype is not an emergency response service and does not provide diagnosis or treatment recommendations. Do not enter real health information.</p></section></div></>}
  </>}
  <div hidden={view !== 'Tasks' || selected !== null}><CareTasks key={resetKey} state={workflow} dispatch={dispatchWorkflow} openPerson={name=>{const p=patients.find(p=>p.name===name);if(p)person(p);}} openAlert={()=>{navigate('Alerts');setAlertFilter('All');}}/></div><footer className="footer"><span>CareGrid by HomeClinicStore</span><span>Next-Gen Healthcare at Home.</span></footer></main></div></div>;
}
