'use client';
import {useState,type FormEvent} from 'react';
import {clinicalPillars,type ClinicalPillar} from '../../lib/care-plans';
export type StoredPlan={id:string;person_id:string;focus:string;pillar:ClinicalPillar;owner:string;cadence:string;goals:string;next_review:string;status:string;version:number};
export type PlanReview={id:string;plan_id:string;author:string;note:string;at:string};
type LivePerson={id:string;name:string;active:number;pillar?:ClinicalPillar;programme?:string};
type Props={plans:StoredPlan[];reviews:PlanReview[];links:{plan_id:string;version:number;task_id:string}[];people:LivePerson[];users:{id:string;email:string;active?:number}[];busy:boolean;mutate:(data:Record<string,unknown>)=>Promise<boolean>;openTasks:()=>void};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function LiveCarePlans({plans,reviews,links,people,users,busy,mutate,openTasks}:Props){
 const [filter,setFilter]=useState('All'),[pillarFilter,setPillarFilter]=useState<'All pillars'|ClinicalPillar>('All pillars'),[editing,setEditing]=useState<StoredPlan|null>(null),[selectedPersonId,setSelectedPersonId]=useState('');
 const date=today();
 const due=(p:StoredPlan)=>p.status!=='Paused'&&p.next_review<=date;
 const visible=plans.filter(p=>(filter==='All'||(filter==='Due for review'?due(p):p.status===filter))&&(pillarFilter==='All pillars'||p.pillar===pillarFilter));
 const inheritedPillar=people.find(p=>p.id===selectedPersonId)?.pillar||'Diabetes management';
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const fields=Object.fromEntries(new FormData(form));if(await mutate({...fields,action:editing?'plan-update':'plan',...(editing?{id:editing.id,version:editing.version}:{})})){setEditing(null);setSelectedPersonId('');form.reset();}}
 return <>
 <section className="panel"><div className="panel-heading"><div><h2>Care plans</h2><p>Document the agreed support workflow, owner, clinical pillar and next review. No clinical thresholds are generated.</p></div><span className="badge">{plans.filter(due).length} due for review</span></div><div className="filters"><label className="field">Status<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Due for review','Active','Needs review','Paused'].map(value=><option key={value}>{value}</option>)}</select></label><label className="field">Clinical pillar<select value={pillarFilter} onChange={e=>setPillarFilter(e.target.value as 'All pillars'|ClinicalPillar)}><option>All pillars</option>{clinicalPillars.map(({name})=><option key={name}>{name}</option>)}</select></label></div>
 {!visible.length&&<div className="empty"><h3>No matching care plans</h3><p>Create a plan below or change the filters.</p></div>}
 {visible.map(plan=>{const person=people.find(p=>p.id===plan.person_id);const owner=users.find(u=>u.id===plan.owner);const linked=links.some(l=>l.plan_id===plan.id&&l.version===plan.version);return <article className="care-plan" key={plan.id}>
 <div className="panel-heading"><div><span className="eyebrow">{plan.pillar}</span><h3>{plan.focus}</h3><p>{person?.name} · {plan.status}{!person?.active?' · Monitoring paused':''}</p></div><span className={`badge ${due(plan)?'amber':''}`}>{due(plan)?'Review due':`Review ${plan.next_review}`}</span></div>
 <dl><div><dt>Owner</dt><dd>{owner?.email}{!owner?.active?' · Account disabled':''}</dd></div><div><dt>Cadence</dt><dd>{plan.cadence}</dd></div><div><dt>Clinical pillar</dt><dd>{plan.pillar}</dd></div></dl><p className="plan-goals">{plan.goals}</p>
 <div className="actions"><button className="secondary" disabled={busy} onClick={()=>setEditing(plan)}>Edit plan</button><button className="secondary" disabled={busy||plan.status==='Paused'||!person?.active} onClick={async()=>{if(linked){openTasks();return;}if(await mutate({action:'plan-task',id:plan.id,version:plan.version}))openTasks();}}>{linked?'View follow-up':'Create plan follow-up'}</button></div>
 <details><summary>Record a review</summary><p>Review notes document team activity and do not enter device readings.</p><form className="live-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await mutate({...Object.fromEntries(new FormData(form)),action:'plan-review',id:plan.id,version:plan.version}))form.reset();}}><label className="field">Review note<textarea name="note" required maxLength={2000} rows={3}/></label><label className="field">Next review date<input type="date" name="nextReview" required/></label><button className="primary" disabled={busy||plan.status==='Paused'||!person?.active}>Save review</button></form></details>
 <details><summary>Review history ({reviews.filter(r=>r.plan_id===plan.id).length})</summary>{reviews.filter(r=>r.plan_id===plan.id).map(r=><div key={r.id} className="review-entry"><strong>{users.find(u=>u.id===r.author)?.email}</strong><small>{new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Johannesburg'}).format(new Date(r.at))} SAST</small><p className="plan-goals">{r.note}</p></div>)}</details>
 </article>;})}</section>
 <section className="panel"><h2>{editing?'Edit care plan':'Create a care plan'}</h2>{editing&&<p>Editing version {editing.version}. If another team member changes this plan, refresh before saving.</p>}<form className="live-form" key={editing?`${editing.id}-${editing.version}`:'new'} onSubmit={save}>
 {!editing&&<label className="field">Person<select required name="personId" value={selectedPersonId} onChange={e=>setSelectedPersonId(e.target.value)}><option value="">Choose a person</option>{people.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
 <label className="field">Clinical pillar<select key={editing?.id||selectedPersonId||'default'} required name="pillar" defaultValue={editing?.pillar||inheritedPillar}>{clinicalPillars.map(({name})=><option key={name}>{name}</option>)}</select></label><p className="muted">New plans start with the selected person’s pathway. Change it only when the care workflow intentionally belongs to another pillar.</p><label className="field">Plan focus<input required maxLength={160} name="focus" defaultValue={editing?.focus}/></label><label className="field">Plan owner<select required name="owner" defaultValue={editing?.owner||''}><option value="">Choose an owner</option>{users.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select></label><label className="field">Review cadence<input required name="cadence" maxLength={160} placeholder="For example, weekly review" defaultValue={editing?.cadence}/></label><label className="field">Next review date<input name="nextReview" type="date" required defaultValue={editing?.next_review}/></label><label className="field">Plan status<select name="status" defaultValue={editing?.status||'Active'}><option>Active</option><option>Needs review</option><option>Paused</option></select></label><label className="field">Agreed goals<textarea name="goals" required rows={3} maxLength={2000} defaultValue={editing?.goals}/></label><button className="primary" disabled={busy}>{editing?'Save plan changes':'Create care plan'}</button>{editing&&<button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel editing</button>}</form></section>
 </>;
}
