'use client';

import Link from 'next/link';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, HeartPulse } from 'lucide-react';

type Person={id:string;name:string};type Row=Record<string,unknown>;type Snapshot={people:Person[];assessments:Row[]};
async function req(method='GET',body?:unknown){const response=await fetch('/api/workspace/',{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
export default function RtmPage(){const [data,setData]=useState<Snapshot|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function refresh(){try{setData(await req());setMessage('');}catch(error){setMessage((error as Error).message);}}useEffect(()=>{refresh();},[]);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget;try{const fields=Object.fromEntries(new FormData(form));await req('POST',{...fields,action:'assessment'});form.reset();await refresh();setMessage('Patient-reported check-in saved.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
const people=<><option value="">Choose a person</option>{data?.people.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</>;
return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><HeartPulse/> Therapeutic Monitoring</div></header><section className="clinical-hero"><span className="eyebrow">REMOTE THERAPEUTIC MONITORING</span><h1>Capture symptoms, therapy adherence and patient-reported outcomes.</h1><p>These records complement device readings and care plans without turning patient-reported data into automated diagnosis or treatment advice.</p></section>{message&&<p className="live-notice">{message}</p>}{data&&<><section className="clinical-section"><h2>Record patient-reported check-in</h2><form className="live-form" onSubmit={submit}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Measure<select name="instrument"><option>Pain check-in</option><option>Fatigue check-in</option><option>Sleep check-in</option><option>Mood check-in</option><option>Exercise completion</option><option>Medication adherence</option><option>Therapy completion</option><option>Home exercise program</option><option>Custom patient-reported outcome</option></select></label><label className="field">Version<input name="version" defaultValue="1"/></label><label className="field">Score / completion value<input name="score" type="number" step="0.01"/></label><label className="field">Response JSON<textarea name="responses" rows={4} placeholder='{"note":"patient-reported response"}'/></label><button className="primary" disabled={busy}>Save check-in</button></form></section><section className="clinical-section"><h2>Recent therapeutic / assessment records</h2><div className="clinical-grid">{data.assessments.slice(0,30).map((row,index)=><article className="clinical-card" key={String(row.id||index)}><span className="eyebrow">{String(row.instrument||'Assessment')}</span><h3>Score {row.score===null||row.score===undefined?'—':String(row.score)}</h3><p>{String(row.completed_at||'')}</p></article>)}</div></section></>}</div></main>}
