'use client';
import { useState } from 'react';
import { Activity, LayoutDashboard, Users, Bell, Radio, Settings, ArrowUpRight, ArrowLeft, Search, Check, ChevronRight, ShieldCheck, RotateCcw } from 'lucide-react';
import { alerts, patients, filterPatients, toggleAcknowledgement, type Patient } from '../lib/demo';
type View = 'Overview' | 'People' | 'Alerts' | 'Devices' | 'Workspace';
const navigation = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'People', icon: Users }, { label: 'Alerts', icon: Bell }, { label: 'Devices', icon: Radio }, { label: 'Workspace', icon: Settings }] as const;
function Trend({ patient }: { patient: Patient }) {
  const low = Math.min(...patient.readings) - 1, range = Math.max(...patient.readings) - low + 1;
  const points = patient.readings.map((v, i) => `${20 + i * 60},${150 - (v - low) / range * 115}`).join(' ');
  return <figure className="trend"><svg viewBox="0 0 460 180" role="img" aria-label={`${patient.metric} sample trend: ${patient.readings.join(', ')} ${patient.unit}`}><path d="M20 35H440M20 90H440M20 145H440" stroke="#e1e8ed" strokeDasharray="4 5" /><polyline points={points} fill="none" stroke="currentColor" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" />{patient.readings.map((v, i) => <circle key={i} cx={20 + i * 60} cy={150 - (v - low) / range * 115} r="3.5" fill="currentColor" />)}</svg><figcaption>Eight illustrative readings · sequence, not elapsed time</figcaption></figure>;
}
export default function CareGrid() {
  const [view, setView] = useState<View>('Overview');
  const [selected, setSelected] = useState<Patient | null>(null);
  const [query, setQuery] = useState('');
  const [programme, setProgramme] = useState('All programmes');
  const [acknowledged, setAcknowledged] = useState<string[]>([]);
  const [alertFilter, setAlertFilter] = useState('Open');
  const [status, setStatus] = useState('');
  const openAlerts = alerts.filter(a => !acknowledged.includes(a.id));
  const filtered = filterPatients(query, programme);
  function navigate(next: View) { setView(next); setSelected(null); setStatus(''); }
  function acknowledge(id: string) { const was = acknowledged.includes(id); setAcknowledged(ids => toggleAcknowledgement(ids, id)); setStatus(was ? 'Sample alert reopened.' : 'Sample alert acknowledged. No patient contact or clinical action was performed.'); }
  function person(p: Patient) { setSelected(p); setView('People'); }
  function roster(list: Patient[]) { return <div className="roster">{list.map(p => <button className="person" key={p.id} onClick={() => person(p)}><span className="avatar">{p.initials}</span><span className="person-name"><strong>{p.name}</strong><small>{p.id} · {p.town}</small></span><span className="programme">{p.programme}</span><span className={`badge ${p.connected ? 'good' : 'amber'}`}>{p.connected ? 'Device available' : 'Connection check'}</span><ChevronRight size={17} /></button>)}</div>; }
  function alertList() { const list = alerts.filter(a => alertFilter === 'All' || (alertFilter === 'Acknowledged' ? acknowledged.includes(a.id) : !acknowledged.includes(a.id))); return <><div className="tabs" aria-label="Filter alerts">{['Open', 'Acknowledged', 'All'].map(f => <button key={f} aria-pressed={alertFilter === f} onClick={() => setAlertFilter(f)}>{f}</button>)}</div>{list.length ? <div className="alerts">{list.map(a => { const p = patients.find(p => p.id === a.patientId)!; const done = acknowledged.includes(a.id); return <article className="alert" key={a.id}><span className={`alert-symbol ${done ? 'done' : ''}`}>{done ? <Check size={21} /> : a.kind === 'device' ? <Radio size={21} /> : <Activity size={21} />}</span><div><small>{a.time} SAST · {p.id}</small><h3>{a.title}</h3><button className="text-button" onClick={() => person(p)}>{p.name} <ArrowUpRight size={14} /></button><p>{a.description}</p><div className="actions"><button className="secondary" onClick={() => acknowledge(a.id)}>{done ? 'Reopen sample alert' : 'Acknowledge'}</button><span className={`badge ${done ? 'good' : 'amber'}`}>{done ? 'Acknowledged' : 'Awaiting review'}</span></div></div></article>; })}</div> : <div className="empty"><Check size={30} /><h3>No {alertFilter.toLowerCase()} alerts</h3><p>Change the filter to explore the sample workflow.</p></div>}</>; }
  return <div className="shell"><a className="skip" href="#main">Skip to workspace</a><aside className="sidebar"><a className="brand" href="./"><span className="brand-mark"><Activity size={25} /></span>Care<span>Grid</span></a><p className="workspace-label">HOMECLINICSTORE / CARE TEAM</p><nav aria-label="Main navigation">{navigation.map(({ label, icon: Icon }) => <button key={label} onClick={() => navigate(label)} aria-current={view === label ? 'page' : undefined}><Icon size={19} /><span>{label}</span>{label === 'Alerts' && openAlerts.length > 0 && <b>{openAlerts.length}</b>}</button>)}</nav><div className="sidebar-note"><ShieldCheck size={23} /><strong>A space for considered care.</strong><p>Connected devices. Clear context. People first.</p></div><div className="team"><span className="avatar">HC</span><div><strong>HomeClinicStore</strong><small>Demonstration workspace</small></div></div></aside><div className="workspace"><header className="topbar"><span>Workspace <ChevronRight size={13} /> <strong>{selected ? selected.name : view}</strong></span><span className="demo-pill">Demo environment</span></header><main id="main"><div className="demo-notice"><span className="dot" /><span>Fictional people and sample readings. No live monitoring or clinical decisions. Changes reset on refresh.</span></div><div role="status" className={status ? 'status' : 'sr-only'}>{status}</div>
  {selected ? <><button className="text-button back" onClick={() => setSelected(null)}><ArrowLeft size={16} /> Back to people</button><div className="page-heading"><div><span className="eyebrow">PERSON / {selected.id}</span><h1>{selected.name}</h1><p>{selected.programme} · {selected.town}, South Africa</p></div><span className="badge">Fictional profile</span></div><div className="detail-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">{selected.metric}</span><h2>{selected.readings.at(-1)} <small>{selected.unit}</small></h2></div><span className="muted">Sample · {selected.last}</span></div><Trend patient={selected} /><details><summary>View accessible reading table</summary><table><thead><tr><th>Sequence</th><th>{selected.metric} ({selected.unit})</th></tr></thead><tbody>{selected.readings.map((v,i) => <tr key={i}><td>{i+1}</td><td>{v}</td></tr>)}</tbody></table></details></section><section className="panel"><span className="eyebrow">CONNECTED DEVICE</span><h2>{selected.device}</h2><dl><div><dt>Status</dt><dd>{selected.connected ? 'Available in demo' : 'Connection check'}</dd></div><div><dt>Battery</dt><dd>{selected.battery}%</dd></div><div><dt>Latest sample</dt><dd>{selected.last} SAST</dd></div></dl><p className="muted">Device status is illustrative. No physical device is paired with this workspace.</p></section></div><section className="panel context"><h2>Context before action.</h2><p>In a production care service, interpretation and follow-up depend on a clinician-agreed plan, measurement context and verified device data. This demo does not classify readings or recommend treatment.</p><button className="secondary" onClick={() => { navigate('Alerts'); setAlertFilter('All'); }}>Explore sample review tasks <ArrowUpRight size={16} /></button></section></> : <>
  <div className="page-heading"><div><span className="eyebrow">CONNECTED CARE AT HOME</span><h1>{view === 'Overview' ? 'A clearer view of care.' : view === 'People' ? 'People, not just readings.' : view === 'Alerts' ? 'Attention, with context.' : view === 'Devices' ? 'The connections behind care.' : 'Your care workspace.'}</h1><p>{view === 'Overview' ? 'A considered starting point for your team’s day.' : view === 'People' ? 'Explore the people and programmes in this sample workspace.' : view === 'Alerts' ? 'Review and acknowledge sample tasks. Acknowledgement is not resolution.' : view === 'Devices' ? 'Understand device availability before interpreting missing readings.' : 'A transparent foundation for a connected-care service.'}</p></div><span className="date">14 September 2026 <small>Sample day · SAST (UTC+2)</small></span></div>
  {view === 'Overview' && <><div className="metrics"><article><span>People in the workspace</span><strong>{patients.length.toString().padStart(2,'0')}</strong><small>Across two sample programmes</small></article><article><span>Awaiting review</span><strong>{openAlerts.length.toString().padStart(2,'0')}<i /></strong><small>Sample tasks for your team</small></article><article><span>Devices available</span><strong>03 <em>/ 04</em></strong><small>One connection to check</small></article></div><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">YOUR NEXT STEP</span><h2>Review queue</h2></div><button className="text-button" onClick={() => navigate('Alerts')}>View all <ArrowUpRight size={16} /></button></div>{openAlerts.length ? openAlerts.map(a => <button className="queue-item" key={a.id} onClick={() => navigate('Alerts')}><span className="queue-dot" /><span><strong>{a.title}</strong><small>{patients.find(p=>p.id===a.patientId)?.name} · {a.time} SAST</small></span><ChevronRight size={18} /></button>) : <div className="empty">All sample tasks acknowledged.</div>}</section><section className="feature-panel"><span className="eyebrow">THE CAREGRID APPROACH</span><h2>Good care starts<br />with the whole picture.</h2><p>Bring device readings and the people behind them into one considered workflow.</p><div className="flow"><span>Device</span><ChevronRight size={15} /><span>Context</span><ChevronRight size={15} /><span>Care team</span></div><button onClick={() => navigate('Workspace')}>About this workspace <ArrowUpRight size={17} /></button></section></div><section className="panel"><div className="panel-heading"><h2>People in view</h2><button className="text-button" onClick={() => navigate('People')}>Explore people <ArrowUpRight size={16} /></button></div>{roster(patients)}</section></>}
  {view === 'People' && <section className="panel"><div className="filters"><label className="search"><Search size={18} /><span className="sr-only">Search name, ID or town</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID or town" /></label><label><span className="sr-only">Programme</span><select value={programme} onChange={e=>setProgramme(e.target.value)}><option>All programmes</option><option>Glucose monitoring</option><option>Blood pressure</option></select></label><span className="muted" role="status">{filtered.length} people</span></div>{filtered.length ? roster(filtered) : <div className="empty"><Search size={26} /><h2>No matching people</h2><p>Try a different name, town or programme.</p><button className="secondary" onClick={()=>{setQuery('');setProgramme('All programmes');}}>Clear filters</button></div>}</section>}
  {view === 'Alerts' && <section className="panel">{alertList()}</section>}
  {view === 'Devices' && <div className="device-grid">{patients.map(p=><article className="panel" key={p.id}><div className="panel-heading"><span className="device-icon"><Radio size={26} /></span><span className={`badge ${p.connected?'good':'amber'}`}>{p.connected?'Available':'Check connection'}</span></div><h2>{p.device}</h2><button className="text-button" onClick={()=>person(p)}>{p.name}<ArrowUpRight size={14}/></button><dl><div><dt>Demo identifier</dt><dd>DEV-{p.id}</dd></div><div><dt>Battery</dt><dd>{p.battery}%</dd></div><div><dt>Last sample</dt><dd>{p.last}</dd></div></dl><meter min={0} max={100} value={p.battery} aria-label={`${p.name} device battery`} /><p className="muted">Illustrative status · no device connection</p></article>)}</div>}
  {view === 'Workspace' && <div className="detail-grid"><section className="panel"><span className="eyebrow">FIRST RELEASE</span><h2>Built around a human workflow.</h2><p>CareGrid brings sample people, measurements and review tasks together so you can evaluate the care-team experience before connecting real services.</p><dl><div><dt>Organisation</dt><dd>HomeClinicStore</dd></div><div><dt>Region</dt><dd>South Africa</dd></div><div><dt>Time zone</dt><dd>Africa/Johannesburg</dd></div><div><dt>Data mode</dt><dd>Fictional samples only</dd></div></dl><button className="secondary" onClick={()=>{setAcknowledged([]);setQuery('');setProgramme('All programmes');setAlertFilter('Open');setStatus('Demo reset. All sample alerts are open again.');}}><RotateCcw size={16}/> Reset demo activity</button></section><section className="panel"><span className="eyebrow">BEFORE REAL-WORLD USE</span><h2>The next layer is trust.</h2><ul className="readiness"><li>Authenticated accounts and role-based access</li><li>Consent, privacy controls and retention rules</li><li>Verified device integrations and data provenance</li><li>Clinician-agreed alert and response workflows</li><li>Secure audit history and operational support</li></ul><p className="muted">This prototype has no login, backend, patient messaging or emergency response service. Do not enter real health information.</p></section></div>}
  </>}
  <footer className="footer"><span>CareGrid by HomeClinicStore</span><span>Next-Gen Healthcare at Home.</span></footer></main></div></div>;
}
