'use client';

import Link from 'next/link';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Cable, KeyRound, Webhook } from 'lucide-react';

type Row=Record<string,unknown>;type Snapshot={apiClients:Row[];webhooks:Row[];connectors:Row[];integrationEvents:Row[]};
async function req(method='GET',body?:unknown){const response=await fetch('/api/workspace/',{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
export default function Integrations(){const [data,setData]=useState<Snapshot|null>(null);const [message,setMessage]=useState('');const [secret,setSecret]=useState('');const [busy,setBusy]=useState(false);async function refresh(){try{setData(await req());setMessage('');}catch(error){setMessage((error as Error).message);}}useEffect(()=>{refresh();},[]);async function submit(action:string,event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setSecret('');const form=event.currentTarget;try{const result=await req('POST',{...Object.fromEntries(new FormData(form)),action});if(result.secret)setSecret(result.secret);form.reset();await refresh();setMessage('Changes saved.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><Cable/> API & Integrations</div></header><section className="clinical-hero"><span className="eyebrow">FHIR · HL7 · REST · WEBHOOKS</span><h1>Connect CareGrid without coupling the platform to one vendor.</h1><p>Connector records describe integrations; production connectivity still requires verified external credentials, mappings and end-to-end tests.</p></section>{message&&<p className="live-notice">{message}</p>}{secret&&<section className="clinical-section clinical-safety"><h2>Copy this secret now</h2><p className="credential">{secret}</p><p>CareGrid stores only a hash; this value is not returned again.</p></section>}
 {data&&<><section className="metrics"><article><span>Connectors</span><strong>{data.connectors.length}</strong></article><article><span>API clients</span><strong>{data.apiClients.length}</strong></article><article><span>Webhooks</span><strong>{data.webhooks.length}</strong></article><article><span>Integration events</span><strong>{data.integrationEvents.length}</strong></article></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">API ACCESS</span><h2>Create API client</h2></div><KeyRound/></div><form className="live-form" onSubmit={e=>submit('api-client',e)}><label className="field">Client name<input name="name" required/></label><label className="field">Scopes JSON<textarea name="scopes" rows={4} placeholder='["read:people","read:observations"]'/></label><button className="primary" disabled={busy}>Create client</button></form></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">EVENT DELIVERY</span><h2>Register webhook</h2></div><Webhook/></div><form className="live-form" onSubmit={e=>submit('webhook',e)}><label className="field">Webhook name<input name="name" required/></label><label className="field">Event type<input name="eventType" required placeholder="reading.accepted"/></label><label className="field">Target URL<input name="targetUrl" type="url" required/></label><button className="primary" disabled={busy}>Register webhook</button></form></section>
 <section className="clinical-section"><h2>Connector registry</h2><div className="clinical-grid">{data.connectors.map((row,index)=><article className="clinical-card" key={String(row.id||index)}><span className="eyebrow">{String(row.connector_type||'connector')}</span><h3>{String(row.name||'Unnamed connector')}</h3><p>{String(row.status||'disabled')} · {String(row.endpoint||'endpoint not configured')}</p></article>)}</div></section></>}
 </div></main>}
