'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, HeartHandshake, MessageCircle, ShieldCheck } from 'lucide-react';
import type { AutomaticReading } from '../../../lib/ingestion/reading';

type Person={id:string;name:string;town:string;pillar:string;programme:string;active:number};type Row=Record<string,unknown>;type Reading={person_id:string;measured_at:string;payload:AutomaticReading};type Plan={person_id:string;focus:string;goals:string;next_review:string;status:string};type Snapshot={people:Person[];readings:Reading[];plans:Plan[];appointments:Row[];educationAssignments:Row[];communications:Row[];notifications:Row[]};
function value(reading:Reading){const m=reading.payload.measurement;if(m.kind==='blood-pressure')return `${m.systolic}/${m.diastolic} ${m.unit}`;return `${m.value} ${m.unit}`;}
export default function PatientPortalPreview(){const [data,setData]=useState<Snapshot|null>(null);const [personId,setPersonId]=useState('');const [message,setMessage]=useState('');useEffect(()=>{fetch('/api/workspace/',{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Sign in to open the portal preview.');setData(body);setPersonId(body.people?.[0]?.id||'');}).catch(error=>setMessage(error.message));},[]);const context=useMemo(()=>{if(!data||!personId)return null;const person=data.people.find(p=>p.id===personId);if(!person)return null;const match=(rows:Row[])=>rows.filter(row=>String(row.person_id||'')===personId);return{person,readings:data.readings.filter(r=>r.person_id===personId),plans:data.plans.filter(p=>p.person_id===personId),appointments:match(data.appointments||[]),education:match(data.educationAssignments||[]),communications:match(data.communications||[]),notifications:match(data.notifications||[])};},[data,personId]);
return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><HeartHandshake/> Patient Portal</div></header><section className="clinical-hero"><span className="eyebrow">PATIENT EXPERIENCE PREVIEW</span><h1>A simpler view of CareGrid for the person receiving care.</h1><p>This preview is intentionally staff-authenticated. Dedicated patient identity, invitation, consent and account-recovery policy must be configured before exposing it directly to patients.</p></section>{message&&<p className="live-notice">{message}</p>}{data&&<section className="clinical-section"><label className="field">Preview person<select value={personId} onChange={e=>setPersonId(e.target.value)}>{data.people.map(person=><option value={person.id} key={person.id}>{person.name}</option>)}</select></label></section>}{context&&<><section className="clinical-section clinical-safety"><div className="clinical-section-heading"><div><span className="eyebrow">YOUR CARE</span><h2>{context.person.name}</h2></div><ShieldCheck/></div><p>{context.person.pillar} · {context.person.programme} · {context.person.active?'Monitoring active':'Monitoring paused'}</p></section><section className="metrics"><article><span>Recent readings</span><strong>{context.readings.length}</strong></article><article><span>Care plans</span><strong>{context.plans.length}</strong></article><article><span>Appointments</span><strong>{context.appointments.length}</strong></article><article><span>Education items</span><strong>{context.education.length}</strong></article></section><section className="clinical-section"><h2>Recent measurements</h2><div className="clinical-grid">{context.readings.slice(0,12).map((reading,index)=><article className="clinical-card" key={`${reading.measured_at}-${index}`}><span className="eyebrow">{reading.payload.measurement.kind.replaceAll('-',' ')}</span><h3>{value(reading)}</h3><p>{new Date(reading.measured_at).toLocaleString('en-ZA')}</p></article>)}</div></section><section className="clinical-section"><h2>My care plans</h2><div className="clinical-grid">{context.plans.map((plan,index)=><article className="clinical-card" key={`${plan.focus}-${index}`}><h3>{plan.focus}</h3><p>{plan.goals}</p><small>{plan.status} · Next review {plan.next_review}</small></article>)}</div></section><section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">STAY CONNECTED</span><h2>Messages, reminders and appointments</h2></div><MessageCircle/></div><p>{context.communications.length} communication records · {context.notifications.length} reminders · {context.appointments.length} appointments.</p><p className="muted">Clinical interpretations and emergency-response advice are not generated in this portal preview.</p></section></>}</div></main>}
