'use client';

import Link from 'next/link';
import { useEffect, useState, type FormEvent } from 'react';
import { Activity, ArrowLeft, BellRing, BookOpenCheck, CalendarDays, HeartHandshake } from 'lucide-react';

type Person={id:string;name:string};type Row=Record<string,unknown>;type Snapshot={people:Person[];notifications:Row[];education:Row[];educationAssignments:Row[];consents:Row[];appointments:Row[];contacts:Row[]};
async function req(method='GET',body?:unknown){const response=await fetch('/api/workspace/',{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
export default function Engagement(){const [data,setData]=useState<Snapshot|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function refresh(){try{setData(await req());setMessage('');}catch(error){setMessage((error as Error).message);}}useEffect(()=>{refresh();},[]);async function submit(action:string,event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget;try{await req('POST',{...Object.fromEntries(new FormData(form)),action});form.reset();await refresh();setMessage('Changes saved.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 const people=<><option value="">Choose a person</option>{data?.people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</>;
 return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><HeartHandshake/> Patient Engagement</div></header><section className="clinical-hero"><span className="eyebrow">ENGAGEMENT & ENROLLMENT</span><h1>Keep outreach, consent and education connected to the person.</h1><p>CareGrid stores the engagement workflow even when delivery providers such as SMS, email, push or video are configured separately.</p></section>{message&&<p className="live-notice">{message}</p>}
 {data&&<><section className="metrics"><article><span>Notification records</span><strong>{data.notifications.length}</strong></article><article><span>Education items</span><strong>{data.education.length}</strong></article><article><span>Consent records</span><strong>{data.consents.length}</strong></article><article><span>Appointments</span><strong>{data.appointments.length}</strong></article></section>
 <section className="clinical-section"><h2>Person contact details</h2><form className="live-form" onSubmit={e=>submit('person-contact',e)}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Phone<input name="phone"/></label><label className="field">Email<input name="email" type="email"/></label><label className="field">Address<input name="address"/></label><label className="field">Emergency contact<input name="emergencyName"/></label><label className="field">Emergency phone<input name="emergencyPhone"/></label><button className="primary" disabled={busy}>Save contacts</button></form></section>
 <section className="clinical-section"><h2>Program consent</h2><form className="live-form" onSubmit={e=>submit('consent',e)}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Program<input name="programme"/></label><label className="field">Consent type<input name="consentType" required placeholder="RPM monitoring"/></label><label className="field">Version<input name="version" required placeholder="2026-09"/></label><label className="field">Status<select name="status"><option>granted</option><option>declined</option><option>withdrawn</option></select></label><button className="primary" disabled={busy}>Record consent</button></form></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">REMINDERS</span><h2>Queue engagement notification</h2></div><BellRing/></div><form className="live-form" onSubmit={e=>submit('notification',e)}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Channel<select name="channel"><option>sms</option><option>email</option><option>push</option><option>portal</option></select></label><label className="field">Notification type<input name="notificationType" required placeholder="reading-reminder"/></label><label className="field">Template key<input name="templateKey"/></label><label className="field">Schedule<input name="scheduledAt" type="datetime-local"/></label><button className="primary" disabled={busy}>Queue notification</button></form></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">EDUCATION</span><h2>Create education content reference</h2></div><BookOpenCheck/></div><form className="live-form" onSubmit={e=>submit('education-item',e)}><label className="field">Title<input name="title" required/></label><label className="field">Category<input name="category"/></label><label className="field">Content reference<input name="contentReference" required placeholder="approved content URL or storage reference"/></label><label className="field">Pillar<input name="pillar"/></label><label className="field">Program<input name="programme"/></label><button className="primary" disabled={busy}>Add education item</button></form><form className="live-form" onSubmit={e=>submit('education-assignment',e)}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Education item ID<input name="educationId" required/></label><button className="primary" disabled={busy}>Assign education</button></form></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">APPOINTMENTS</span><h2>Schedule or import appointment</h2></div><CalendarDays/></div><form className="live-form" onSubmit={e=>submit('appointment',e)}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Starts at<input name="startsAt" type="datetime-local" required/></label><label className="field">Provider ID<input name="providerId"/></label><label className="field">Site ID<input name="siteId"/></label><label className="field">Status<select name="status"><option>scheduled</option><option>completed</option><option>cancelled</option></select></label><label className="field">Notes<textarea name="notes" rows={3}/></label><button className="primary" disabled={busy}>Save appointment</button></form></section></>}
 </div></main>}
