'use client';

import Link from 'next/link';
import { useEffect, useState, type FormEvent } from 'react';
import { Activity, ArrowLeft, PackageCheck, Radio, Truck } from 'lucide-react';

type Row=Record<string,unknown>;type Person={id:string;name:string};
type Snapshot={people:Person[];deviceCatalogue:Row[];deviceInventory:Row[];deviceAssignments:Row[];deviceShipments:Row[]};
async function req(method='GET',body?:unknown){const response=await fetch('/api/workspace/',{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
export default function DeviceOperations(){const [data,setData]=useState<Snapshot|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function refresh(){try{setData(await req());setMessage('');}catch(error){setMessage((error as Error).message);}}useEffect(()=>{refresh();},[]);async function submit(action:string,event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget;try{await req('POST',{...Object.fromEntries(new FormData(form)),action});form.reset();await refresh();setMessage('Changes saved.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 const people=<><option value="">Choose a person</option>{data?.people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</>;
 return <main className="clinical-page"><div className="clinical-shell"><header className="clinical-header"><Link className="clinical-back" href="/platform/"><ArrowLeft size={16}/> Platform hub</Link><div className="clinical-brand"><Radio/> Device Operations</div></header><section className="clinical-hero"><span className="eyebrow">CONNECTED DEVICE LIFECYCLE</span><h1>From catalogue to home assignment.</h1><p>Track device models, inventory, patient assignment, firmware, warranty and shipment state without altering existing reading history.</p></section>{message&&<p className="live-notice">{message}</p>}
 {data&&<><section className="metrics"><article><span>Catalogue models</span><strong>{data.deviceCatalogue.length}</strong></article><article><span>Inventory units</span><strong>{data.deviceInventory.length}</strong></article><article><span>Assignments</span><strong>{data.deviceAssignments.length}</strong></article><article><span>Shipments</span><strong>{data.deviceShipments.length}</strong></article></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">CATALOGUE</span><h2>Register supported hardware</h2></div><PackageCheck/></div><form className="live-form" onSubmit={e=>submit('device-catalogue',e)}><label className="field">Manufacturer<input name="manufacturer" required/></label><label className="field">Model<input name="model" required/></label><label className="field">Device type<input name="deviceType" required placeholder="blood pressure, CGM, ECG…"/></label><label className="field">Connectivity<input name="connectivity" placeholder="cellular, Bluetooth, Wi-Fi, gateway"/></label><label className="field">Supported metrics JSON<textarea name="supportedMetrics" rows={3} placeholder='["blood-pressure"]'/></label><button className="primary" disabled={busy}>Add model</button></form></section>
 <section className="clinical-section"><h2>Add inventory unit</h2><form className="live-form" onSubmit={e=>submit('device-inventory',e)}><label className="field">Catalogue ID<input name="catalogueId"/></label><label className="field">Existing CareGrid device ID<input name="deviceId"/></label><label className="field">Serial number<input name="serialNumber"/></label><label className="field">Supplier<input name="supplier"/></label><label className="field">Lot / batch<input name="lotNumber"/></label><label className="field">Warranty end<input name="warrantyEnd" type="date"/></label><label className="field">Lifecycle state<select name="lifecycleState"><option>inventory</option><option>allocated</option><option>active</option><option>repair</option><option>returned</option><option>retired</option></select></label><label className="field">Firmware<input name="firmware"/></label><button className="primary" disabled={busy}>Add inventory</button></form></section>
 <section className="clinical-section"><h2>Assign a device</h2><form className="live-form" onSubmit={e=>submit('device-assignment',e)}><label className="field">Person<select name="personId" required>{people}</select></label><label className="field">Inventory ID<input name="inventoryId"/></label><label className="field">CareGrid device ID<input name="deviceId"/></label><button className="primary" disabled={busy}>Record assignment</button></form></section>
 <section className="clinical-section"><div className="clinical-section-heading"><div><span className="eyebrow">LOGISTICS</span><h2>Shipment tracking</h2></div><Truck/></div><form className="live-form" onSubmit={e=>submit('device-shipment',e)}><label className="field">Inventory ID<input name="inventoryId"/></label><label className="field">Person<select name="personId">{people}</select></label><label className="field">Carrier<input name="carrier"/></label><label className="field">Tracking reference<input name="trackingReference"/></label><label className="field">Status<select name="status"><option>pending</option><option>shipped</option><option>delivered</option><option>returned</option></select></label><button className="primary" disabled={busy}>Save shipment</button></form></section></>}
 </div></main>}
